### PR TITLE
New Hvac Ontology

### PR DESCRIPTION
**Pull request by rrg40305**
This ontology is for every heating, ventilation and air conditioning systems.

### CODE REVIEW

**Comment by amedranogil** [comment]
This ontology was designed in UPM for an internal project. We believe that is generic enough for any heating ventilation and air conditioning system and thus should be part of the official set of ontoligies of universAAL.

**Comment by Alfiva** [comment]
I have only inspected the OWL so far (a diagram would be helpful) but I have several concerns:
-I would expect some inheritance from Device, but there is none (thats not critical)
-StatusValue looks too much like that of Device - couldnt it be reused?
-The concept of Units seems in conflict with our measurement ontology (and I would expect more detail regarding temperatures)
-Both TImer and Units have a member Minutes
-The way they are used as properties is also a bit fuzzy
-The LEVEL enumeration looks very generic. Dont we have something like that already?
-By the way, the code defining the LEVEL in the HvacOntology class is bugged: oci_level is called in more places than it should. And enum members are declared multiple times.

I could accept this pull request and add this ont to our collection, but it will need rework. Are you OK with that?

**Comment by amedranogil** [comment]
Let me answer some points, note that the OWL file was the inspiration but as you have noticed it is not complete (the javacode is).

-I would expect some inheritance from Device, but there is none (thats not critical)
 -- In Java Code the inheritance is there.

-StatusValue looks too much like that of Device - couldnt it be reused?
 -- actually yes, I missed that, @rrg40305 please delete ont.hvac/src/main/java/org/universAAL/ontology/hvac/StatusValue.java and rework to use ont.device/src/main/java/org/universAAL/ontology/device/StatusValue.java It seems to be a duplicate left over.

-The concept of Units seems in conflict with our measurement ontology (and I would expect more detail regarding temperatures)
-- In the Java code the Unit ontology is imported and used correctly (the problem with the provided OWL is that it hasn't imported any of the ontologies, so some place holders where created, this is one of them).

-Both TImer and Units have a member Minutes
-- After thinking carefully about Timer we reached the conclussion yet another ontology was needed to describe Timer (BTW this is NOT a trivial ontology!) Timer has been set as placeholder both on OWL and the Java code. specifically in javacode it is left empty, so there is no need to worry about overlapping.

-The way they are used as properties is also a bit fuzzy
-- Timer is meant to be used as a description of a particular device timer configuration eg: "turn off after 30 minutes" or "turn on at 14:00" or "turn on at 16:00 every weekday and turn off after 2 hours" (hope with these examples you see the complexity of the Timer ontology).

-The LEVEL enumeration looks very generic. Dont we have something like that already?
-- This LEVEL is meant to describe all HVAC devices intensities, which as you know from the device ontology, not all devices have the same options (some have 3, others have 7). I will discuss with @rrg40305 how can he recycle intensity levels from other ontologies.

-By the way, the code defining the LEVEL in the HvacOntology class is bugged: oci_level is called in more places than it should. And enum members are declared multiple times.
-- If we reuse other LEVEL concepts this will not be a problem. But I will recheck the code, not just for this class but the rest of enumerations

I could accept this pull request and add this ont to our collection, but it will need rework. Are you OK with that?
No, don't accept it yet. @rrg40305  will perform the required changes, and once it is compliant, and checked you may accept it.

**Comment by cstockloew** [comment]
> -The LEVEL enumeration looks very generic. Dont we have something like 
> that already?
> -- This LEVEL is meant to describe all HVAC devices intensities, which 
> as you know from the device ontology, not all devices have the same 
> options (some have 3, others have 7). I will discuss with @rrg40305 
> https://github.com/rrg40305 how can he recycle intensity levels from 
> other ontologies.
> 
> Is it possible to use Rating (13 options) or LevelRating (5 options) in 
> DataRep (package org.universAAL.middleware.owl.supply)?

**Comment by amedranogil** [comment]
Thanks @cstockloew , we will look in to those two.

**Comment by amedranogil** [comment]
Please recheck with the updated commits. 
And accept if proceeds.

**Comment by Alfiva** [comment]
Accepted. I also realized that we already had Heater concepts in ont.device, but until we make this ont official we keep them both. Also, no more swing and fan?

**Comment by amedranogil** [comment]
Ok.
We will sort these out before next release.
Swing and Fan where the Level of swing of a ventilation system, and intensity of the fan of a ventilation system; both have been substituted by LevelRating in the appropriate properties.

**Pull request merged**
